blank_issues_enabled: false
contact_links:
  - name: Get help in GitHub Discussions | 功能讨论区
    url: https://github.com/PanDownload-Fix/PanDownload-Fix/discussions
    about: Have a question? Not sure if your issue affects everyone reproducibly? The quickest way to get help is on PanDownload-Fix's GitHub Discussions!