name: Feature request | 新功能提议
description: Please describe in detail the features you expect
title: '[Feature] <title>'
labels: feature request
body:
  - type: checkboxes
    id: ensure
    attributes:
      label: Verify steps
      description: "
在提交之前，请确认
Please verify that you've followed these steps
"
      options:
        - label: "
我已经在 [Issue Tracker](https://github.com/PanDownload-Fix/PanDownload-Fix/labels/feature%20request) 中找过我要提出的请求
I have searched on the [issue tracker](https://github.com/PanDownload-Fix/PanDownload-Fix/labels/feature%20request) for a related feature request.
"
          required: true
        - label: "
我已经仔细看过 [Documentation](https://pandownload.net/) 并无法自行解决问题
I have read the [documentation](https://pandownload.net/) and was unable to solve the issue.
"
          required: true
  - type: textarea
    attributes:
      label: Description
      description: 请详细、清晰地表达你要提出的论述，例如这个问题如何影响到你？你想实现什么功能？目前 伪PanDownload 的行为是什麽？
    validations:
      required: true
  - type: textarea
    attributes:
      label: Possible Solution
      description: "
此项非必须，但是如果你有想法的话欢迎提出。
Not obligatory, but suggest a fix/reason for the bug, or ideas how to implement the addition or change
"